#' Read a plotnik file produced by FAVE as a data frame
#' 
#' \code{read.plotik()} will read plotnik files as generated by FAVE-extract.
#' 
#' @param file A plotnik file to be read in
#' 
#' @export


read.plotnik <- function(file){
  data <- scan(file, blank.lines.skip = F, what = "list", sep = "\n", quiet = T)
  filename <- rev(unlist(strsplit(file, split = "/")))[1]
  
  header.info <- data[1]
  
  last <- (which(unlist(lapply(data, nchar))==0)-1)
  n <- last-3
  data <- data[3:last]
  to.compile <- vector(mode = "list", length = n)
  
  for(i in 1:n){
    bits <- unlist(strsplit(gsub("[<>]", "", data[[i]]), split = "  "))
    to.compile[[i]] <- bits
  }
    
  out <- ldply(to.compile, function(x)unlist(strsplit(x[1], split = ",")))
  colnames(out) <- c("F1","F2","F3","VCoding","Dur_Stress","Info")
  
  out$Word <- suppressWarnings(reshape2::colsplit(out$Info, pattern = " ", names = "Word")$Word)
  if(length(grep("\\.", out$Dur_Stress)) > 0){
	  out <- cbind(out, reshape2::colsplit(out$Dur_Stress, pattern = "\\.", names = c("Stress","Dur_msec")))
	  out$Dur_msec <- as.numeric(out$Dur_msec)
  }else{
      out$Stress <- as.numeric(out$Dur_Stress)	
  }
  
  vcodings <- plt_code(out$VCoding)
  
  out <- cbind(out, vcodings[,-2])
  
  out$Time <- 0
  for(i in 1:nrow(out)){
  	timestr <- rev(unlist(strsplit(out$Info[i], " ")))[1]
  	out$Time[i] <- as.numeric(timestr)
  }
  
  out$F1 <- as.numeric(out$F1)
  out$F2 <- as.numeric(out$F2)
  out$F3 <- as.numeric(out$F3)
  out$Stress <- as.character(out$Stress)
  out$Word <- as.character(out$Word)
  if(length(grep("\\[f\\]", out$Info)) > 0){
    out$Function <- FALSE
    out[grep("\\[f\\]", out$Info),]$Function <- TRUE
  }
  
  out$File <- filename
  
  
  if(length(to.compile[[1]]) > 1){
    tracks <- ldply(to.compile, function(x)unlist(strsplit(x[2], split = ",")))
    if(ncol(tracks)%%2 != 0){
      break
    }
    colnames(tracks) <- paste(rep(c("F1","F2"), ncol(tracks)/2), 
                              rep(1:(ncol(tracks)/2), each = 2), sep = "_")
    out <- cbind(out,tracks)
  }
  
  out <- cbind(data.frame(rbind(unlist(strsplit(header.info, split=",")))), out)
  return(out)
}

