#' Read a plotnik file produced by FAVE as a data frame
#' 
#' \code{read.plotik()} will read plotnik files as generated by FAVE-extract.
#' 
#' @details
#' Plotnik files are idiosyncratically formatted. 
#' The first line provides demographic information for the speaker, 
#' and the second provides a count of the number of measurements.
#' Then lines follow for each measurement, including F1, F2, F3,
#' coding for the vowel using a numerical representation,
#' the stress and duration of the vowel, concatenated with a decimal point,
#' the word, an optional mark to represent whether the vowel was a monophthong,
#' a numerical code for the number of formants, a time stamp, and then F1 an F2 formant tracks.
#' The delimeters between these fields are, variously, commas, periods, spaces, double spaces,
#' right and left angle brackets.
#' 
#' In addition, many plotnik files have more lines at the end of the file representing mean values for each vowel class.
#' These are not processed by \code{read.plotnik()}
#' 
#' @param file Path to a plotnik file to be read in.
#' 
#' @return A data frame
#' 
#' @note
#' The first few columns of the data frame will be named X1, X2, and so on.
#' The data in these columns are drawn from the first line of demographic data, 
#' which we cannot expect to be stable at the moment. 
#' Once the FAVE format has stabilized, the names of these fields will be fixed.
#' 
#' @export
#' @import plyr
#' @import reshape2
#' 
#' @examples
#' \dontrun{
#' # get path to a plotnik file bundled with the package
#' frueh_path <- file.path(.libPaths()[1], 
#'                            "FAVErtools",
#'                                "extdata",
#'                                    "PH06-2-A-JosefFruehwald.plt")
#' frueh <- read.plotnik(frueh_path)
#' }


read.plotnik <- function(file){
  data <- scan(file, blank.lines.skip = F, what = "list", sep = "\n", quiet = T)
  filename <- rev(unlist(strsplit(file, split = "/")))[1]
  
  header.info <- data[1]
  
  last <- (which(unlist(lapply(data, nchar))==0)-1)
  n <- last-3
  data <- data[3:last]

  to.compile <- llply(data, function(x)unlist(strsplit(gsub("[<>]", "", x), split = "  ")))
      
  out <- ldply(to.compile, function(x)unlist(strsplit(x[1], split = ",")))
  colnames(out) <- c("F1","F2","F3","VCoding","Dur_Stress","Info")
  
  infos <- strsplit(out$Info, split=" ")
  no_marks <- which(sapply(infos, length)==3)
  for(i in no_marks){
    infos[[i]] <- c(infos[[i]][1], NA, infos[[i]][2:3])
  }
  infos_df <- ldply(llply(infos, rbind), data.frame,stringsAsFactors=F)
  colnames(infos_df) <- c("Word","Mark","nFormants","Time")
  infos_df$Time <- as.numeric(infos_df$Time)
  
  out <- cbind(out, infos_df)
  
  
  if(length(grep("\\.", out$Dur_Stress)) > 0){
	  out <- cbind(out, reshape2::colsplit(out$Dur_Stress, pattern = "\\.", names = c("Stress","Dur_msec")))
	  out$Dur_msec <- as.numeric(out$Dur_msec)
  }else{
      out$Stress <- as.numeric(out$Dur_Stress)	
  }
  
  vcodings <- plt_code(out$VCoding)
  
  out <- cbind(out, vcodings[,-2])
    
  out$F1 <- as.numeric(out$F1)
  out$F2 <- as.numeric(out$F2)
  out$F3 <- as.numeric(out$F3)
  out$Stress <- as.character(out$Stress)
  out$Word <- as.character(out$Word)
  if(length(grep("\\[f\\]", out$Info)) > 0){
    out$Function <- FALSE
    out[grep("\\[f\\]", out$Info),]$Function <- TRUE
  }
  
  out$File <- filename
  
  if(length(to.compile[[1]]) > 1){
    tracks <- ldply(to.compile, function(x)unlist(strsplit(x[2], split = ",")))
    if(ncol(tracks)%%2 != 0){
      break
    }
    colnames(tracks) <- paste(rep(c("F1","F2"), ncol(tracks)/2), 
                              rep(1:(ncol(tracks)/2), each = 2), sep = "_")
    out <- cbind(out,tracks)
  }
  
  out <- cbind(data.frame(rbind(unlist(strsplit(header.info, split=",")))), out)
  return(out)
}

